name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu22
    steps:
      - uses: actions/checkout@v3.5.1
      - uses: erlef/setup-beam@v1.15.4
        with:
          otp-version: "28.0"
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test --target=erlang
      - run: gleam test --target=javascript
